---
title: FailFastException
ms.custom: 
ms.date: 03/30/2017
ms.prod: .net-framework
ms.reviewer: 
ms.suite: 
ms.technology: dotnet-clr
ms.tgt_pltfrm: 
ms.topic: article
ms.assetid: f30de0d9-3a91-4800-9d09-3504d7e5a10f
caps.latest.revision: "8"
author: dotnet-bot
ms.author: dotnetcontent
manager: wpickett
ms.workload: dotnet
ms.openlocfilehash: deff4cd29e2a7a0ab2f50dcaf30c787a5856a8dc
ms.sourcegitcommit: 16186c34a957fdd52e5db7294f291f7530ac9d24
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 12/22/2017
---
# <a name="failfastexception"></a>FailFastException
Id: 103  
  
 Gravedad: error  
  
 Categoría: seguimiento  
  
## <a name="description"></a>Descripción  
 Se inició una excepción durante FailFast. El evento enumera la excepción, el nombre del proceso y el id. del mismo.  
  
## <a name="see-also"></a>Vea también  
 [Registro de eventos](../../../../../docs/framework/wcf/diagnostics/event-logging/index.md)  
 [Referencia general de eventos](../../../../../docs/framework/wcf/diagnostics/event-logging/events-general-reference.md)
