---
title: Bloque 'Catch' nunca se alcanzó. <exception> se gestionó anteriormente en la misma instrucción 'Try'
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 3bbb76264ba28f7f74e1ec626adf2c09a50273d4
ms.sourcegitcommit: bef803e2025642df39f2f1e046767d89031e0304
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 02/15/2019
ms.locfileid: "56304328"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>Bloque 'Catch' nunca se alcanzó. \<excepción > se gestionó anteriormente en la misma instrucción 'Try'
Un bloque `Catch` del código no se puede alcanzar porque se controla en un bloque `Try` precedente.  
  
De forma predeterminada, este mensaje es una advertencia. Para más información sobre cómo ocultar las advertencias o cómo tratarlas como errores, vea [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).
  
 **Identificador de error:** BC42031  
  
## <a name="to-correct-this-error"></a>Para corregir este error  
  
-   Quite la instrucción redundante.  
  
## <a name="see-also"></a>Vea también

- [Cómo usar el bloque try/catch para detectar excepciones](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Utilizar controladores de excepciones filtradas por el usuario](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [Try...Catch...Finally (instrucción)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
